### ISSUE TITLE
Example Config

### ISSUE THREAD

**Issue by tomq0608** [incinirate/Xenon#2]
Hi, there is no example config

**Comment by incinirate** [comment]
https://github.com/incinirate/Xenon/blob/master/examples/config.lua

Yes there is

**Comment by tomq0608** [comment]
Oh, it’s because the setup points to a different link

Sent from my iPad

On 30 Jun 2018, at 20:14, Bryan <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #2<https://github.com/incinirate/Xenon/issues/2>.
