### ISSUE TITLE
Ordering 16+ stacks of an item causes a crash

### ISSUE THREAD

**Issue by ozzt** [incinirate/Xenon#7]
****What's the bug?****
When ordering 16+ stacks of an item, a crash occurs and gives no items.

https://i.ozzt.pw/e0GMB.mp4

I am using Xenon 1.2.0.

****How to reproduce****
There are two ways to reproduce this.

Method 1:
1. Fill every slot on the turtle except for one.
2. Order 2 stacks of an item.

Method 2:
1. Order 16+ stacks of an item.

**Comment by incinirate** [comment]
Pushed a new release that should correct this behavior
